defmodule AshPki.Resource.RevocationList.Info do
  @moduledoc """
  Introspection helpers for `AshPki.Resource.RevocationList`.

  Generated by `Spark.InfoGenerator`. Each option in the `pki` DSL
  section is exposed as `pki_<option>/1`:

      AshPki.Resource.RevocationList.Info.pki_certificate_authority(MyApp.RevocationList)
      # => MyApp.CertificateAuthority

      AshPki.Resource.RevocationList.Info.pki_certificate(MyApp.RevocationList)
      # => MyApp.Certificate

  Falls back to the shipped `AshPki.*` defaults when the resource
  doesn't declare a `pki` block.
  """

  use Spark.InfoGenerator,
    extension: AshPki.Resource.RevocationList,
    sections: [:pki]
end
