defmodule Mix.Tasks.AshPki.Init do
  @shortdoc "Bootstrap a CA hierarchy and write trust material to priv/pki"

  @moduledoc """
  Generates a root CA, an intermediate CA, and a server cert + key suitable
  for terminating mTLS in front of the Ash app. Writes everything to
  `priv/pki/` of the calling app.

      mix ash_pki.init [--out priv/pki] \\
                      [--root-cn "AshPki Root CA"] \\
                      [--intermediate-cn "AshPki Intermediate CA"] \\
                      [--server-cn "localhost"] \\
                      [--validity-days 3650]

  Re-running the task overwrites the contents of `--out`. The resources
  generated by this task live in ETS by default — operators using AshPostgres
  should run their migrations first and the rows will persist.
  """

  use Mix.Task

  @switches [
    out: :string,
    root_cn: :string,
    intermediate_cn: :string,
    server_cn: :string,
    validity_days: :integer
  ]

  @impl Mix.Task
  def run(args) do
    Mix.Task.run("app.start")

    {opts, _} = OptionParser.parse!(args, strict: @switches)

    out = Keyword.get(opts, :out, "priv/pki")
    root_cn = Keyword.get(opts, :root_cn, "AshPki Root CA")
    intermediate_cn = Keyword.get(opts, :intermediate_cn, "AshPki Intermediate CA")
    server_cn = Keyword.get(opts, :server_cn, "localhost")
    validity_days = Keyword.get(opts, :validity_days, 365 * 10)

    File.mkdir_p!(out)

    Mix.shell().info("==> Generating root CA: #{root_cn}")
    {:ok, root} =
      AshPki.CertificateAuthority.create_root(
        "root",
        "/CN=#{root_cn}",
        %{validity_days: validity_days}
      )

    Mix.shell().info("==> Generating intermediate CA: #{intermediate_cn}")
    {:ok, intermediate} =
      AshPki.CertificateAuthority.create_intermediate(
        "intermediate",
        root.id,
        "/CN=#{intermediate_cn}",
        %{validity_days: round(validity_days / 2)}
      )

    Mix.shell().info("==> Generating server cert: CN=#{server_cn}")
    server_key = X509.PrivateKey.new_ec(:secp256r1)
    server_csr = X509.CSR.new(server_key, "/CN=#{server_cn}")
    server_csr_pem = X509.CSR.to_pem(server_csr)

    {:ok, server_cert} =
      AshPki.Certificate.issue(intermediate.id, server_csr_pem, %{
        template: :server,
        validity_days: 365,
        subject_alt_names: [server_cn]
      })

    AshPki.Persistence.dump!(out)
    Mix.shell().info("    wrote #{Path.join(out, "ash_pki.json")} (CA store)")

    write!(out, "root_ca.pem", root.certificate_pem)
    write!(out, "intermediate_ca.pem", intermediate.certificate_pem)
    write!(out, "server_cert.pem", server_cert.certificate_pem)
    write!(out, "server_chain.pem", server_cert.certificate_pem <> intermediate.certificate_pem)
    write!(out, "server_key.pem", X509.PrivateKey.to_pem(server_key))
    write!(out, "trust_bundle.pem", root.certificate_pem <> intermediate.certificate_pem)

    Mix.shell().info("""

    ==> Done. Trust material written to #{out}/

      root_ca.pem            ─ pin into device firmware
      intermediate_ca.pem    ─ served alongside server cert during TLS handshake
      server_cert.pem        ─ leaf cert for the Ash app endpoint
      server_chain.pem       ─ leaf + intermediate (for cowboy/Bandit `:certfile`)
      server_key.pem         ─ private key for the Ash app endpoint
      trust_bundle.pem       ─ root + intermediate (for `:cacertfile`)

    Next steps:
      * Configure your Bandit endpoint with the server_chain.pem / server_key.pem.
      * Pin trust_bundle.pem on clients that should trust this hierarchy.
      * Use `mix ash_pki.gen.cert --issuer intermediate --subject "/CN=device-001"` to
        issue device certs against the intermediate.
    """)
  end

  defp write!(out, name, contents) do
    path = Path.join(out, name)
    File.write!(path, contents)
    Mix.shell().info("    wrote #{path}")
  end
end
