defmodule AshPki.Resource.CertificateAuthority.Info do
  @moduledoc """
  Introspection helpers for `AshPki.Resource.CertificateAuthority`.

  Generated by `Spark.InfoGenerator`. Each option in the `pki` DSL
  section is exposed as `pki_<option>/1`:

      AshPki.Resource.CertificateAuthority.Info.pki_certificate(MyApp.CertificateAuthority)
      # => MyApp.Certificate

      AshPki.Resource.CertificateAuthority.Info.pki_revocation_list(MyApp.CertificateAuthority)
      # => MyApp.RevocationList

  Falls back to the shipped `AshPki.*` defaults when the resource
  doesn't declare a `pki` block.
  """

  use Spark.InfoGenerator,
    extension: AshPki.Resource.CertificateAuthority,
    sections: [:pki]
end
