defmodule AshPki.Resource.Certificate.Info do
  @moduledoc """
  Introspection helpers for `AshPki.Resource.Certificate`.

  Generated by `Spark.InfoGenerator`, so each option in the `pki` DSL
  section is exposed as `pki_<option>/1` on this module:

      AshPki.Resource.Certificate.Info.pki_certificate_authority(MyApp.Certificate)
      # => MyApp.CertificateAuthority

  Falls back to the option's default (`AshPki.CertificateAuthority`)
  when the resource doesn't declare a `pki` block.
  """

  use Spark.InfoGenerator,
    extension: AshPki.Resource.Certificate,
    sections: [:pki]
end
